Флексы на главной страницы
htmlacademy-htmlcss/1813461-technomart-31 pull request #9
Opened 2021-06-12 10:26 UTC by IgnatSergey

2021-06-14 17:40 UTC, mouxez requested changes

2021-06-14 17:40 UTC, mouxez commented on css/style.css
> +.manufacturersLogo {
название класса не правильного формата

2021-06-14 17:40 UTC, mouxez commented on css/style.css
> +.manufacturersLogo {
проверь везде

2021-06-14 17:40 UTC, mouxez commented on css/style.css
>  .navigation-footer-list a[href]:hover,
достаточно сложный селектор для чтения
его точно нельзя оптимизировать?

2021-06-14 17:40 UTC, mouxez commented on css/style.css
> +  height: 114px;
задавать строгую высоту - не очень хороший подход
лучше min-height

2021-06-14 17:40 UTC, mouxez commented on css/style.css
> +  /* width: 220px;
перед проверкой удаляй все комменты

2021-06-15 16:25 UTC, IgnatSergey commented on css/style.css
> +  height: 114px;
не совсем понимаю зачем в многострочном поле ввода использовать именно min-height, ведь при переполнении текстом появится прокрутка

2021-06-15 16:26 UTC, IgnatSergey commented on css/style.css
>  .navigation-footer-list a[href]:hover,
тут ничего другого придумать не могу

2021-06-19 03:47 UTC, merged